### ISSUE TITLE
napalm-procurve does not work with napalm 2.5

### ISSUE THREAD

**Issue by mnhauke** [ixs/napalm-procurve#10]
Napalm added MTU support for "get_interfaces" in their latest release [napalm 2.5](https://github.com/napalm-automation/napalm/releases/tag/2.5.0)

This issue can be easily triggered by running napalm-procurve's unit tests against napalm 2.5.0

Here a logfile with the output from napalm-procurve's failed unit tests:
[napalm-procurve-broken-build-napalm25-buildlog-openSUSE-tumbleweed.txt](https://github.com/ixs/napalm-procurve/files/3821717/napalm-procurve-broken-build-napalm25-buildlog-openSUSE-tumbleweed.txt)

**Comment by ixs** [comment]
Thanks for that report.

I did a quick fix in <https://github.com/ixs/napalm-procurve/commit/2b1a6af8f53464fdf6cef0c8c9dad1db9d429847>. This works on my hardware but I have not run the full testsuite unter napalm 2.5 as I need to run out.

Please see if this fixes your issue and report back. Thank you.

**Comment by mnhauke** [comment]
2b1a6af seems to fix the MTU issue but running the full testsuite still gives some errors:
[napalm-procurve-still-broken-build-napalm25-buildlog-openSUSE-tumbleweed.txt](https://github.com/ixs/napalm-procurve/files/3825224/napalm-procurve-still-broken-build-napalm25-buildlog-openSUSE-tumbleweed.txt)

**Comment by ixs** [comment]
@mnhauke hmmm. I think that was already covered.
There's a new 0.5.0 release, check if that one works for you.

**Comment by mnhauke** [comment]
bb49b52 fixes the issue. Thanks!
As far as I can see napalm-procurve 0.5.0 is working fine with napalm 2.5.0 now.

A quick test against napalm 2.4.0 shows that at least not all unit tests with this older version of napalm will pass but I'm not sure if it's worth to do the change in a backwards compatible way.

**Comment by ixs** [comment]
@mnhauke As far as I can see, the unit test fails because the expected return values changed between 2.4.0 and 2.5.0.

I would not even know how to change the returns accordingly depending on version...

So thanks for the report, 0.5.0 with 2.5.0 is the way to go then.
