### ISSUE TITLE
napalm-procurve doesn't work with napalm 3.0.0

### ISSUE THREAD

**Issue by MeggyCal** [ixs/napalm-procurve#11]
AFAIK there are two issues.

First, napalm has dropped Python2  and with it the class py23_compat. In napalm-procurve there is only py23_compat.text_type used, it is the same as str in Python3 (see [1]). Therefore "sed -i 's/py23_compat.text_type/str/g'" on all affected files should resolve this.

Second, napalm has added a (not mandatory) parameter 'sanitized' to get_config (see [2]) and they are running a test on it. But there are no data for the test in napalm-procurve, so it fails. Sorry, I have no clue how should the data look like.

Could you please take a look? Thanks!

[1] https://github.com/napalm-automation/napalm/commit/9d27a00788f031455171b901741fb257cc640d8f
[2] https://github.com/napalm-automation/napalm/commit/5003cfcffaef439ceebd278478a2a2f96d0cfbe3

**Comment by ixs** [comment]
Hi @MeggyCal,

thank you for your report. The search-and-replace suggestion was accurate. Thanks for that.
The code is now supporting the sanitized parameter but does not actually do anything about that. The idea is that "sensitive" data like passwords and authentication strings get stripped. Good idea, should probably do that but needs a bit more work.
Right now however the test suite works again, which is nice.

There's a new release 0.6.0 that fixes your issue. Please try it out and see if you're happy.

Thanks,
 Andreas
