### ISSUE TITLE
Publish package on pypi.org

### ISSUE THREAD

**Issue by jobec** [ixs/napalm-procurve#3]
It would be nice to have this package publish on [PyPi](https://pypi.org) also.

**Comment by ixs** [comment]
Ohh man. I've never done that. Let me see what I can do. :-)

**Comment by jobec** [comment]
This one explains at all nicely:
https://packaging.python.org/tutorials/packaging-projects/

**Comment by ixs** [comment]
https://pypi.org/project/napalm-procurve/

This should do the trick I believe.
