### ISSUE TITLE
Building a package results in an error.

### ISSUE THREAD

**Issue by jobec** [ixs/napalm-procurve#4]
When building this package, it gives the below error.
```
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'
```

**Comment by jobec** [comment]
This is related to https://github.com/pypa/pip/issues/4696

An option would be to not try to read the requirements.txt file but just copy it's contents into `install_requires` in `setup.py`

**Comment by ixs** [comment]
Interesting. Worked fine for me. What pip version did you use? I just tried on a centos machine with an older pip (9.0.1) and it seems to work fine there.

**Comment by jobec** [comment]
Upgrade your pip version to the latest version, and you'll see it explodes.
